"""
Test that validates the code generated by ThalosCodingAgentCore.

This test:
1. Generates code using the agent
2. Executes the generated code
3. Tests the validation logic in the generated code
"""

import sys
import tempfile
import os
from thalos_coding_agent_core import ThalosCodingAgentCore, CodeRequest, GenerationMode


def test_generated_code_execution():
    """Test that generated code can be executed and works correctly."""
    print("\n" + "="*60)
    print("TESTING GENERATED CODE EXECUTION")
    print("="*60 + "\n")
    
    # Generate code
    agent = ThalosCodingAgentCore()
    request = CodeRequest(
        query='Create validation module',
        mode=GenerationMode.FULL_APPLICATION,
        language='python',
        complexity=7,
        attached_files=[]
    )
    
    artifact = agent.generate(request)
    generated_code = artifact.code
    
    # Write to temporary file and execute
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
        f.write(generated_code)
        temp_file = f.name
    
    try:
        # Import the generated module
        import importlib.util
        spec = importlib.util.spec_from_file_location("generated_module", temp_file)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        print("✓ Generated code imports successfully")
        
        # Test DefaultValidator
        validator = module.DefaultValidator()
        
        # Test 1: Valid payload
        try:
            validator.validate({"key": "value"})
            print("✓ Valid payload accepted")
        except Exception as e:
            print(f"✗ Valid payload rejected: {e}")
            return False
        
        # Test 2: Reserved key rejection
        try:
            validator.validate({"_meta": "reserved"})
            print("✗ Reserved key not rejected")
            return False
        except ValueError:
            print("✓ Reserved key correctly rejected")
        
        # Test 3: Oversized payload
        try:
            oversized = {f"key_{i}": i for i in range(1001)}
            validator.validate(oversized)
            print("✗ Oversized payload not rejected")
            return False
        except ValueError:
            print("✓ Oversized payload correctly rejected")
        
        # Test 4: String length limit
        try:
            validator.validate({"key": "x" * 100001})
            print("✗ Overlong string not rejected")
            return False
        except ValueError:
            print("✓ Overlong string correctly rejected")
        
        # Test 5: Nesting depth
        try:
            # Create deeply nested structure (11 levels)
            payload = {"level0": {}}
            current = payload["level0"]
            for i in range(1, 11):
                current[f"level{i}"] = {}
                current = current[f"level{i}"]
            validator.validate(payload)
            print("✗ Excessive nesting not rejected")
            return False
        except ValueError:
            print("✓ Excessive nesting correctly rejected")
        
        # Test ThalosAgent
        config = module.Config(mode="test", debug=False)
        agent = module.ThalosAgent(config)
        
        # Test 6: Agent execution
        try:
            result = agent.execute({"test": "data"})
            if result["status"] == "success":
                print("✓ Agent executes successfully")
            else:
                print(f"✗ Agent returned unexpected status: {result['status']}")
                return False
        except Exception as e:
            print(f"✗ Agent execution failed: {e}")
            return False
        
        # Test 7: Agent validation failure handling
        try:
            agent.execute({"_system": "reserved"})
            print("✗ Agent didn't reject invalid payload")
            return False
        except ValueError:
            print("✓ Agent correctly rejects invalid payload")
        
        # Test 8: Transform payload
        try:
            transformed = agent._transform_payload({"key": "value"})
            if transformed == {"key": "value"}:
                print("✓ Transform payload works correctly")
            else:
                print(f"✗ Transform payload returned unexpected result: {transformed}")
                return False
        except Exception as e:
            print(f"✗ Transform payload failed: {e}")
            return False
        
        print("\n" + "="*60)
        print("✓ ALL TESTS PASSED")
        print("="*60 + "\n")
        return True
        
    finally:
        # Clean up
        os.unlink(temp_file)


if __name__ == "__main__":
    success = test_generated_code_execution()
    sys.exit(0 if success else 1)
